### DISCUSSION TITLE
How to publish

### DISCUSSION THREAD

**Discussion by thewh1teagle** [napi-rs/napi-rs#2087] [General]
It took me a while to understand how to publish it to multiple platforms and the docs / tooling of this project needs a lot of improvement about that.

### How to publish?
1. Choose new name for your package and ensure it's available in [npmjs.com](https://www.npmjs.com/)
2. If you chose to use `scoped` name eg. `@twitter/hello` you need to register the scope `twitter` in  [npmjs.com/org/create](https://www.npmjs.com/org/create)
3. Create new Github repository
4. Create npm access token in your npm account at `https://www.npmjs.com/settings/<username>/tokens`
5. Add the token as `NPM_TOKEN` to your repo secrets at `https://github.com/<username>/<repo name>/settings/secrets/actions`
6. Follow [docs/introduction/simple-package](https://napi.rs/docs/introduction/simple-package) and create it with the package name your chose. 
7. After build it locally, navigate to each folder inside `npm` folder in the project, and run `npm publish --access public` once (keep the versions as `0.0.0` just once)
8. Execute once `yarn install`
9. Push your changes to Github (the CI will run automatically)

That's it.
When you push again new version, change **only** the main `package.json`, don't change the versions inside `npm` folder - the CI will trigger `prepublishOnly` scripts which does that.

#### Monorepo
If you're in a monorepo and the package in subfolder, you will need to tweak `CI.yaml`
eg. adding `cache-dependency-path: <folder path of package>` to every setup of node  
eg. fixing volume mounts of `Docker`
And also on top of your workflow set 
```yaml
defaults:
  run:
    working-directory: <package path>
```

#### Caching errors in node setup with node@20

Add 

```yaml
env:
   DISABLE_V8_COMPILE_CACHE: 1
```
To setup-node which uses v20

You may also need to fix the last publish action to download the artifacts to the right folder:

```yaml
- name: Download all artifacts
  uses: actions/download-artifact@v4
   with:
       path: ./bindings/node/artifacts
```

Support `x86_64-apple-darwin`:

```yaml
          - host: macos-latest
            target: x86_64-apple-darwin
-           build: yarn build
+           build: yarn build --target x86_64-apple-darwin
```
