### DISCUSSION TITLE
npm publish questions

### DISCUSSION THREAD

**Discussion by shaozi** [napi-rs/napi-rs#2315] [General]
Hi,

This is my first time use napi to publish to npm. however, I am a little bit confused on the current CI steps. Please correct me if I am wrong:

It seems in CI.yml the following steps downloads artifacts (.node files) to folder `artifacts` and later move them to `npm` folder:

```yml
    - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Move artifacts
        run: yarn artifacts
```

Then when publishing, the `.npmignore` file actually ignored all `*.node` files. The actual `.node` files were instead published individually into npm with the same version number. (Is this the reason the document recommend creating a name scope?)

Then in the generated `index.js` file, it checks the platform, and require the corresponding`.node` file. It searches two locations: 
- it checks local file, if it exists, require it
- other wise, require it as it is a npm module

My question is: why not simply copy the artifacts to the project folder, and publish them together with the package itself? The index.js will have no problem to load them, and it does not have any complexity of separated published packages.
