### ISSUE TITLE
自动话出错failed to run custom build command for `openssl-sys v0.9.72`

### ISSUE THREAD

**Issue by ChinaMars521** [napi-rs/napi-rs#1100]
failed to run custom build command for `openssl-sys v0.9.72`
android 版本 ios 版本

**Comment by ChinaMars521** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/76717950/158790302-d8541bfb-98c4-4e0b-a611-e0d00c308326.png">
错误版本

**Comment by ChinaMars521** [comment]
Error: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by Brooooooklyn** [comment]
这个是你依赖的库在这些平台编译有问题，跟 NAPI-RS 项目无关

**Comment by messense** [comment]
https://docs.rs/openssl/latest/openssl/#vendored

如果要交叉编译 OpenSSL，建议启用 `vendored` feature.

```toml
[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
```
