### ISSUE TITLE
JS object missing functions if other functions return Option

### ISSUE THREAD

**Issue by shachlanAmazon** [napi-rs/napi-rs#1214]
If this rust code is built using `yarn build`, and ran using the JS code below it, node fails (error also below).
Rust:
```rust
use napi_derive::napi;

#[napi(js_name = "Sample")]
struct JsSample {}

#[napi]
impl JsSample {
  #[napi]
  pub async fn create_connection() -> JsSample {
    let client = redis::Client::open("redis://foobar.com:6379").unwrap();
    let _connection = client.get_multiplexed_async_connection().await.unwrap();
    JsSample{ }
  }

  #[napi]
  pub async fn get(&self, key: String) -> Option<String> {
    Some(key)
  }
}
```

If the code of `get` is changed to not return an option, the problem disappears.

Working Rust:

```rust
  #[napi]
  pub async fn get(&self, key: String) -> String {
    key
  }
```

Weirdly enough, the issue also disappears if the client/connection creation is removed, or replaced with other async calls, such as `tokio::time::sleep`, or if `get` is made into a non-async function.

JS:
```js
const index = require('./index');
const Sample = index.Sample;
async function foo() {
  const sample = await Sample.createConnection();
  console.log(await sample.get("foo"));
}
foo();
```
error:
```
/home/ubuntu/repositories/elasticache-clients-performance-blog-code/redis-napi-test/foo.js:4
  const sample = await Sample.createConnection();
                              ^

TypeError: Cannot read properties of undefined (reading 'createConnection')
    at foo (/home/ubuntu/repositories/elasticache-clients-performance-blog-code/redis-napi-test/foo.js:4:31)
    at Object.<anonymous> (/home/ubuntu/repositories/elasticache-clients-performance-blog-code/redis-napi-test/foo.js:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

Toml file:
```toml
[package]
authors = ["foobar <foo@bar.com>"]
edition = "2021"
name = "napi-package-template"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3.21"
redis = { version = "0.21.5", features = ["aio", "tokio-comp"] }
tokio-util = { version = "0.7", optional = true }
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread", "time"] }
stopwatch = "0.0.7"
timer = "0.2.0"
rand = "0.8.5"
libffi = "3.0.0"
napi = {version = "2", features = ["tokio_rt"] }
napi-derive = "2.5"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
```
