### ISSUE TITLE
ThreadsafeFunction not calling callback with value.

### ISSUE THREAD

**Issue by shachlanAmazon** [napi-rs/napi-rs#1216]
Hi, I'm trying to use `ThreadsafeFunction` as a way to resolve a promise in Rust, but the value that I send to the callback isn't received in JS. In the sample this happens on the calling thread, but I see the same behavior happening also when the callback is called from a spawned future.

### expected console log:
```
[Function: get]
Value is right in rust: 0.5
result: 0.5
```

### received console log:
```
[Function: get]
Value is right in rust: 0.5
result: null
```

### Rust Code:
```rs
use napi_derive::napi;
use napi::{
  threadsafe_function::{ErrorStrategy, ThreadsafeFunction, ThreadsafeFunctionCallMode}, JsFunction,
};

#[napi]
pub fn get(callback: JsFunction) {
  let tsfn: ThreadsafeFunction<f64, ErrorStrategy::CalleeHandled> = callback
    .create_threadsafe_function(0, |ctx| {
      println!("Value is right in rust: {}", ctx.value);
      ctx.env.create_double(ctx.value).map(|s| vec![s])
    }).unwrap();
  tsfn.call(Ok(0.5), ThreadsafeFunctionCallMode::NonBlocking);
}
```
### JS Code:
```js
const { get } = require('./index')
console.log(get); // to verify that I got a concrete function

function get_wrapper() {
  return new Promise((resolve) => {
    get(resolve)
  })
}

async function get_async() {
  console.log('result: ' + (await get_wrapper()))
}

get_async()
```

### TOML file:
```toml
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "napi-package-template"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "2", features = ["tokio_rt"] }
napi-derive = "2"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
```
