### ISSUE TITLE
cli fails with cargo workspace-inheritance

### ISSUE THREAD

**Issue by universalmind303** [napi-rs/napi-rs#1328]
`Type Error: Could not parse the Cargo.toml`

napi commands will fail if using workspace inheritance within your toml file. 

```toml
[package]
edition = "2021"
version.workspace = true 
```

**Comment by Brooooooklyn** [comment]
here is `--cargo-cwd` flag for this scenario https://napi.rs/docs/cli/build

**Comment by messense** [comment]
@Brooooooklyn I don't think that will help, it seems that the `toml` Nodejs package doesn't support the `version.workspace = true` syntax:

```javascript
> var toml = require('toml');
undefined
> toml
{ parse: [Function: parse] }
> toml.parse(`[package]
... edition = "2021"
... version.workspace = true `)
Uncaught [SyntaxError: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.] {
  expected: [
    { type: 'literal', value: '=', description: '"="' },
    { type: 'class', value: '[ \\t]', description: '[ \\t]' },
    {
      type: 'class',
      value: '[A-Za-z0-9_\\-]',
      description: '[A-Za-z0-9_\\-]'
    }
  ],
  found: '.',
  offset: 34,
  line: 3,
  column: 8
}
```

**Comment by messense** [comment]
@universalmind303 Perhaps you can workaround it by writing it as

```toml
[package]
edition = "2021"
version = { workspace = true }
```
