### ISSUE TITLE
electron application crash in windows 

### ISSUE THREAD

**Issue by polin-x** [napi-rs/napi-rs#1341]
It crashe on some windows without vcruntime

**Comment by Brooooooklyn** [comment]
On Windows make sure you have Microsoft Visual C++ Redistributable installed. https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

**Comment by Brooooooklyn** [comment]
> Can you package the DLL of VCRuntime

It's harmful to the download size of all packages

> or use a static library

no, I can't do that. because Node.js native addon itself is the dynamic library.

This problem should only occur on Windows < 10

**Comment by polin-x** [comment]
> > Can you package the DLL of VCRuntime
> 
> 
> 
> It's harmful to the download size of all packages
> 
> 
> 
> > or use a static library
> 
> 
> 
> no, I can't do that. because Node.js native addon itself is the dynamic library.
> 
> 
> 
> This problem should only occur on Windows < 10


I met it in windows10 and windows11.

**Comment by Brooooooklyn** [comment]
Oh, that's weird. I'll investigate it and keep this issue open until I have a  conclusion.

**Comment by niugm** [comment]
I have encountered the same problem, usually, just add a vcruntime140.dll, it can be solved.
You can also enable the compile option crt-static

```toml
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
```

You can use the tool CFF Explorer.exe to confirm the dependent system DLL
