### ISSUE TITLE
openssl causes build error with some of the used docker images

### ISSUE THREAD

**Issue by m1212e** [napi-rs/napi-rs#1359]
on x86_64-unknown-linux-gnu
```
The following warnings were emitted during compilation:

warning: build/expando.c:1:10: fatal error: 'openssl/opensslv.h' file not found
warning: #include <openssl/opensslv.h>
warning:          ^~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.77`
```
could this be in connection with this: https://www.openssl.org/blog/blog/2022/11/01/email-address-overflows/ ?

**Comment by imranbarbhuiya** [comment]
Hi, I'm also having the same issue. How did u fixed it?

**Comment by Brooooooklyn** [comment]
@imranbarbhuiya you should use bundled openssl-sys while building your native addon

**Comment by imranbarbhuiya** [comment]
Thanks, I installed it with apt-get before build to fix the issue https://github.com/imranbarbhuiya/img-hasher/blob/main/.github/workflows/continuous-integration.yml#L44

**Comment by imranbarbhuiya** [comment]
Even tho using above workaround fixes the build issue, but it still doesn't works when installing the package on linux. I get `libssl.so.3: cannot open shared object file: No such file or directory` error. Then I tried both
```toml
[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = { version = "0.9.87", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = { version = "0.9.87", features = ["vendored"] }
``` 
and 
```toml
[target.x86_64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.52", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl = { version = "0.10.52", features = ["vendored"] }
```
but build fails at ci with the same error as before
