### ISSUE TITLE
arm-linux交叉编译的问题和建议

### ISSUE THREAD

**Issue by wacdev** [napi-rs/napi-rs#1594]
现有的arm交叉编译的方式会导致一些东西编译不过，比如

https://github.com/wactax/img2jpg/actions/runs/4991133712/jobs/8937224320

```
      /usr/bin/clang  -ffunction-sections -fdata-sections -fPIC --target=aarch64-unknown-linux-musl  CMakeFiles/cmTC_4222d.dir/testCCompiler.c.o -o cmTC_4222d 
      /usr/bin/ld: unrecognised emulation mode: aarch64linux
      Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386pep i386pe
```

<img width="1640" alt="image" src="https://github.com/napi-rs/napi-rs/assets/127726508/0307c155-4bf8-450e-8fb4-9d904336384e">

而我在亚马逊arm的vps测试编译是可以过的，研究了下是路径的问题，而且很难解决，我搞了半天没搞定

建议用虚拟机编译arm

用起来也很简单, 直接用 https://github.com/docker/build-push-action (最后不用push即可)

platforms可以指定，          platforms: linux/amd64,linux/arm64

```
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
```
