### ISSUE TITLE
[napi-rs/cli] support generate github workflow files in monorepo style

### ISSUE THREAD

**Issue by HomyeeKing** [napi-rs/napi-rs#1602]
the default generated CI file is consider it's a root project, but it may be used as a package of a monorepo project

I've tried set `defaults`, but didn't work
```yaml
# ..
defaults:
  run:
    working-directory: ${{my custom work dir}}
# ..
```
