### ISSUE TITLE
Bug: Mac Universal CI build fail due to updated CPU arch

### ISSUE THREAD

**Issue by HuakunShen** [napi-rs/napi-rs#2076]
GitHub runner now uses M1 mac for `macos-latest`. Not sure when this upgrade was but it seems to break the CI where `x86_64-apple-darwin` and `universal-apple-darwin` is used.

[GitHub Runner List](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

The CI template used to be 

```yml
- host: macos-latest
  target: x86_64-apple-darwin
- host: macos-latest
  target: aarch64-apple-darwin
  build: yarn build --target aarch64-apple-darwin
```

Now it will break on universal build for macos.

See artifacts here https://github.com/CrossCopy/magic-wormhole-napi/actions/runs/8892620497

If you download and unzip [bindings-x86_64-apple-darwin](https://github.com/CrossCopy/magic-wormhole-napi/actions/runs/8892620497/artifacts/1459898534)

Although the zip file name is x86_64, the `.node` file inside is for arm64. 

![image](https://github.com/napi-rs/napi-rs/assets/33727687/242b5d51-55c7-4638-aac5-9d921ac1d5ac)

This result in error

```
Type Error: Some binary files were not found: ["magic-wormhole-napi.darwin-x64.node"]
    at UniversalCommand.<anonymous> (/Users/runner/work/magic-wormhole-napi/magic-wormhole-napi/node_modules/@napi-rs/cli/scripts/index.js:57329:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/magic-wormhole-napi/magic-wormhole-napi/node_modules/@napi-rs/cli/scripts/index.js:3537:56)
```

I suspect this is because M1 Mac now builds arm64 by default with `yarn build`. 

This caused my another previously working project CI to fail if I simply rerun the job.

## Solution

My fix is manually adding a target flag.

```yml
- host: macos-latest
   target: x86_64-apple-darwin
   build: yarn build --target x86_64-apple-darwin
```

`@napi-rs/cli` version is 2.18.2.
