### ISSUE TITLE
napi build doesn't respect alternative target paths

### ISSUE THREAD

**Issue by alshdavid** [napi-rs/napi-rs#2116]
If you change your target folder

```toml
[build]
target-dir = "target/.cargo"
```

napi-rs will fail to copy the artifact. I got around this by patching this code with my actual path

<img width="676" alt="image" src="https://github.com/napi-rs/napi-rs/assets/12656294/7110061f-1ddd-4019-92d5-745e66864ca6">
