### ISSUE TITLE
ThreadSafeFunction cannot be used in Either

### ISSUE THREAD

**Issue by ikkz** [napi-rs/napi-rs#2198]
`Either<String, ThreadSafeFunction>` doesn't impl `FromNapiValue` because ThreadSafeFunction doesn't impl `ValidateNapiValue` according to
https://github.com/napi-rs/napi-rs/blob/327998d0aca2302e516fb2f06ee9ca59f8fc2799/crates/napi/src/bindgen_runtime/js_values/either.rs#L66

I would like to know if it is possible to use ThreadSafeFunction in Either.

test code
``` rust
type TestFunction = ThreadsafeFunction<(i32, i32)>;

#[napi(object, object_to_js = false)]
pub struct Pet {
  pub name: String,
  pub kind: u32,
  pub option_tsfn: Option<Either<String, TestFunction>>,
}

#[napi]
pub fn test(o: Pet) -> i32 {
  println!("hello {0}", o.name);
  return 0;
}
```

My napi versions:
``` toml
[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "3.0.0-alpha.8", default-features = false, features = ["napi4"] }
napi-derive = "3.0.0-alpha.7"

[build-dependencies]
napi-build = "2.1.3"

[profile.release]
lto = true
strip = "symbols"

```
