### ISSUE TITLE
Invert the `noop` feature

### ISSUE THREAD

**Issue by seritools** [napi-rs/napi-rs#2328]
Since features are purely additive in Rust, having a default-enabled feature for generating typings would help when trying to write crates/libs that work both with and without napi (e.g. for testing). Right now that is impossible or at least very unergonomic, as you can't remove napi's `noop` feature:

```toml
[features]
"napi" = ["somehow remove the noop feature here"]
```

You'd have to define all dependent crates with negative features too for it to work.
