### ISSUE TITLE
Update FreeBSD build version

### ISSUE THREAD

**Issue by shaozi** [napi-rs/napi-rs#2345]
FreeBSD is now on 14.1, 13.3 and 13.4, but the CI.yml still uses 13.2.
Also why it runs on `macos-13`? Shouldn't `ubuntu-latest` be more proper?

```yaml
  build-freebsd:
    runs-on: macos-13
    name: Build FreeBSD
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: build
        uses: cross-platform-actions/action@v0.24.0
        env:
          DEBUG: napi:*
          RUSTUP_IO_THREADS: 1
        with:
          operating_system: freebsd
          version: '13.2'
```
