### ISSUE TITLE
No Support For Structs With Generics?

### ISSUE THREAD

**Issue by anshap1719** [napi-rs/napi-rs#2636]
I have a struct with a generic parameter with some trait bounds on it. When I try to use this as a class, a lot of errors are generated.

For example:

```rust
#[derive(napi_derive::napi)]
pub struct TestStruct<Value> where Value: Debug + Serialize + for<'de> Deserialize<'de> + Clone + Send + Sync + 'static, {
    value: Value
}
```

The above code generates a lot of errors, all of which say `Wrong number of type arguments: expected 1, found 0`.

Further inspection revealed that the code generated by `napi` attribute macro is as follows:

```rust
impl napi::bindgen_prelude::TypeName for CacheInstance {
    fn type_name() -> &'static str { "CacheInstance" }
    fn value_type() -> napi::ValueType { napi::ValueType::Function }
}

// ... many more impls are generated with similar signature
```

The generated code does not consider the generic param on the struct. Is there any way to make this work in the existing version of Napi?

For context, here is my dependency config:
```toml
napi = { version = "2.12.2", default-features = false, features = ["napi9", "async", "serde-json", "chrono_date", "tokio_full"] }
napi-derive = { version = "2.12.2" }

[build-dependencies]
napi-build = { version = "2.0.1" }
```
