### ISSUE TITLE
[napi] serde + serde_json serialization / errors

### ISSUE THREAD

**Issue by jaredpalmer** [napi-rs/napi-rs#759]
This code should "just work"

```rust
#[napi]
#[derive(Serialize, Deserialize, Debug)]
struct PackageJson {
  name: String,
  version: String,
  dependencies: Option<HashMap<String, String>>,
}

#[napi]
fn read_package_json() -> Result<PackageJson> {
  let raw = fs::read_to_string("package.json")?;
  let p: PackageJson = serde_json::from_str(&raw)?;
  Ok(p)
}
```

**Comment by Brooooooklyn** [comment]
Enable "serde-json" feature of napi crate, this code will work fine:

```toml
# Cargo.toml

[dependencies]
napi = { version = "2.0.0-alpha.0", features = ["serde-json"] }
```

**Comment by jaredpalmer** [comment]
After adding the serde_json feature, this code yields the error below. Is this intentional?

```rust
use napi::bindgen_prelude::*;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;

#[napi]
#[derive(Serialize, Deserialize, Debug)]
pub struct PackageJson {
    name: String,
    version: String,
    dependencies: Option<HashMap<String, String>>,
    workspaces: Option<Vec<String>>,
    #[serde(rename = "peerDependencies")]
    peer_dependencies: Option<HashMap<String, String>>,
    #[serde(rename = "optionalDependencies")]
    optional_dependencies: Option<HashMap<String, String>>,
    #[serde(rename = "devDependencies")]
    dev_dependencies: Option<HashMap<String, String>>,
}

#[napi]
fn read_package_json(env: Env) -> PackageJson {
    let rdr = fs::read_to_string("package.json").expect("Unable to read package.json");
    let p: PackageJson = serde_json::from_str(&rdr).expect("Unable to read package.json");
    p
}
```

<img width="784" alt="CleanShot 2021-09-24 at 10 36 47@2x" src="https://user-images.githubusercontent.com/4060187/134692906-411ec9c9-556f-4b72-b0c2-c6654dedfe28.png">
r

**Comment by Brooooooklyn** [comment]
It should be resolved in https://github.com/napi-rs/napi-rs/pull/760/files#diff-6377141cf4e29eea9f058ac276890728761b8358bede5999c5b9f4e0a10c5c8cR51-R65

You can change your dependencies to `napi_bindgen` branch:

```toml
[dependencies]
napi = {git = "https://github.com/napi-rs/napi-rs", branch = "napi_bindgen"}
napi-derive = {git = "https://github.com/napi-rs/napi-rs", branch = "napi_bindgen"}
```
