### ISSUE TITLE
[napi-derive] Function `__register__fn__sum_callback__` should have snake_case name

### ISSUE THREAD

**Issue by numToStr** [napi-rs/napi-rs#968]
With the default start template created via `napi new`. I am getting the following diagnostic warning from `rust-analyzer` on the `#[napi]` derive

```
Function `__register__fn__sum_callback__` should have snake_case name, e.g. `__register_fn_sum_callback`
```

#### Cargo.toml
```toml
[dependencies]
napi = { version = "2.0.2", default-features = false, features = ["napi4"] }
napi-derive = "2.0.3"
```

#### rust-analyzer
```
db2a7087b 2021-12-13 stable
```

#### Screenshot
![image](https://user-images.githubusercontent.com/24727447/147361112-6439b577-6047-4dee-b757-fe17073a4b2d.png)
